#ifndef MODESTCOIN_CHAINPARAMSSEEDS_H
#define MODESTCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the modestcoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside a IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x9b,0x8a,0x84,0x70}, 6333},
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x95,0xf8,0x3b,0x8b}, 6333}
};

static SeedSpec6 pnSeed6_test[] = {
};
#endif // MODESTCOIN_CHAINPARAMSSEEDS_H
